name: bip44_coin_constants
description: This package provides BIP44 coin constants.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"
  
dependencies:
  

dev_dependencies:
  test: ^1.15.7
  

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec